apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-fs
---
apiVersion: v1
kind: Pod
metadata:
  name: fs-demo-pod
spec:
  containers:
    - name: web-server
      image: nginx:stable-alpine
      volumeMounts:
        - name: mypvc
          mountPath: /usr/share/nginx/html
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: fs-pvc
